-- WoodVerse first-run seed.
--
-- Run this once in Supabase: SQL Editor -> New query -> paste -> Run.
-- The API also applies the schema on boot, so if the tables do not exist yet, wait
-- for the first deploy to finish and re-run this.
--
-- Safe to run more than once. Every statement is ON CONFLICT DO NOTHING, so a second
-- run changes nothing instead of creating duplicate accounts.
--
-- Accounts created (change these passwords before exposing the site):
--   customer@woodverse.lk / WoodVerse@123
--   vendor@woodverse.lk   / Vendor@12345
--   admin@woodverse.lk    / Admin@12345
--   supplier@woodverse.lk / Supplier@12345

-- ---------------------------------------------------------------- accounts
-- password_hash values are bcrypt, cost 12, generated by bcrypt.hashSync(pw, 12).
-- The server compares with bcrypt.compare (routes/auth.js:147), so these log in
-- through the real login path rather than a dev-only shortcut.
--
-- customer@woodverse.lk mirrors the in-memory account in backend/api/src/data/memory.js.
-- Once DATABASE_URL is set that fallback is bypassed, so the customer role needs a real
-- row here or the storefront cannot be opened at all.
INSERT INTO users (email, full_name, role, password_hash, status) VALUES
  ('customer@woodverse.lk', 'Nimali Perera',   'customer', '$2b$12$wGuVdLevV3AplWbMHZ10o.MgqtGLLm5216XjW4vG8R2m9xw5immni', 'active'),
  ('vendor@woodverse.lk',   'Kasun Fernando',  'vendor',   '$2b$12$CjJ83uvI6qNxkQayULfC/uXIq1wtEFvFdHLXwyfahsX.Q0Lvn97Ii', 'active'),
  ('supplier@woodverse.lk', 'Lumbini Timber',  'supplier', '$2b$12$dodG31zGycUNHGRyJX3OLumJY1EhnRrpR4Q2YmbQiNN6OZyCxEYsW', 'active'),
  ('admin@woodverse.lk',    'Site Admin',      'admin',    '$2b$12$vse7xnTn88MoWF7vMH313.q0uhAoiin.1z2bOI8LW7byfa/AP57MS', 'active')
ON CONFLICT (email) DO NOTHING;

-- ---------------------------------------------------------------- vendors
-- verification_status must be 'approved' or the vendor portal treats the account as
-- not yet trusted. Suppliers reuse the vendors table because a supplier is a vendor
-- of raw material in this model (schema.sql vendors.user_id is UNIQUE).
INSERT INTO vendors (user_id, business_name, verification_status, description)
SELECT u.id, 'Kasun Fernando Woodcraft', 'approved',
       'Bespoke teak, walnut and mahogany furniture made in Moratuwa.'
FROM users u WHERE u.email = 'vendor@woodverse.lk'
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO vendors (user_id, business_name, verification_status, description)
SELECT u.id, 'Lumbini Timber Co.', 'approved',
       'Sustainable timber supplier for certified plantation teak and mahogany.'
FROM users u WHERE u.email = 'supplier@woodverse.lk'
ON CONFLICT (user_id) DO NOTHING;

-- ---------------------------------------------------------------- products
-- Only status='published' rows appear in /api/catalog (routes/catalog.js:26), which is
-- what the storefront and the checkout flow both read. A 'draft' product is invisible
-- to customers but still counts as the vendor's own listing.
--
-- image_url values point at the bundled WebP files, so they resolve on the frontend
-- with no Supabase Storage bucket needed.
INSERT INTO products (vendor_id, name, description, category, material, price, stock_quantity, status, image_url)
SELECT v.id, p.name, p.description, p.category, p.material, p.price, p.stock, 'published', p.image_url
FROM (VALUES
  ('Teak Dining Table',      'Solid reclaimed teak dining table, seats six.',      'furniture', 'Teak',     185000.00::numeric, 8,  '/assets/dining-table-floral.webp'),
  ('Walnut Task Table',      'Walnut desk with cable management and a satin finish.','furniture', 'Walnut',  124500.00::numeric, 12, '/assets/product-walnut-task-table.webp'),
  ('Royal Majesty Sofa Set',  'Three-seat teak sofa set with cane panels.',          'furniture', 'Teak',     640000.00::numeric, 3,  '/assets/royal-majesty-sofa-set.webp'),
  ('Signature Bedframe',      'Mahogany bedframe, king size, solid timber.',         'furniture', 'Mahogany', 298000.00::numeric, 5,  '/assets/signature-bedframe.webp'),
  ('Modular Shelf Unit',      'Five-tier modular shelving in satinwood.',            'furniture', 'Satinwood',  96000.00::numeric, 15, '/assets/product-modular-shelf-unit.webp'),
  ('Carved Jackwood Gift Box','Hand-carved gift box with a sliding lid.',           'gift',      'Jackwood',  24500.00::numeric, 40, '/assets/product-carved-gift-box.webp'),
  ('Bamboo Coaster Set',      'Set of six bamboo coasters with a leather holder.',   'gift',      'Bamboo',     6800.00::numeric, 60, '/assets/product-bamboo-coaster-set.webp'),
  ('Carved Wood Serving Tray', 'Hand-carved serving tray with side handles.',        'gift',      'Mahogany',  15200.00::numeric, 25, '/assets/product-wooden-tray.webp'),
  ('Housewarming Gift Set',   'Curated gift set for new home purchases.',            'gift',      'Mixed',     45000.00::numeric, 18, '/assets/product-housewarming-gift-set.webp')
) AS p(name, description, category, material, price, stock, image_url), vendors v
JOIN users u ON u.id = v.user_id AND u.email = 'vendor@woodverse.lk'
WHERE NOT EXISTS (SELECT 1 FROM products x WHERE x.name = p.name);